package com.triptogether.di

import android.content.Context
import com.triptogether.R
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import javax.inject.Named
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class)
object AppConfigModule {
    /** Web OAuth client id generated by the google-services plugin, needed by Credential Manager. */
    @Provides
    @Singleton
    @Named("googleServerClientId")
    fun provideGoogleServerClientId(
        @ApplicationContext context: Context,
    ): String = context.getString(R.string.default_web_client_id)
}
